
---
AWSTemplateFormatVersion: '2010-09-09'
# Generate a few tables from the tpc-ds dataset in AWS Glue.
# The metadata created in the Data Catalog points to the tpc ds public S3 bucket
#
# Parameters substituted in the Resources section
# These parameters are names of the resources created in the Data Catalog
Parameters:
  CFNDatabaseName:
    Type: String
    Default: tpc_ds_150gb_cf
  CFNTableName1:
    Type: String
    Default: store_sales
  CFNTableName2:
    Type: String
    Default: customer

# Resources to create metadata in the Data Catalog
Resources:
###
# Create an AWS Glue database
  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Ref CFNDatabaseName
        Description: Database for the tpc-ds dataset
###
# Create an AWS Glue table
  StoreSalesTable:
    # Creating the table waits for the database to be created
    DependsOn: GlueDatabase
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref CFNDatabaseName
      TableInput:
        Name: !Ref CFNTableName1
        Description: Define the first few columns of the flights table
        TableType: EXTERNAL_TABLE
        Parameters: {
    "classification": "csv"
  }
        StorageDescriptor:
          OutputFormat: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat
          Columns:
            - Name: ss_sold_date_sk
              Type: bigint
            - Name: ss_sold_time_sk
              Type: bigint
            - Name: ss_item_sk
              Type: bigint
            - Name: ss_customer_sk
              Type: bigint
            - Name: ss_cdemo_sk
              Type: bigint
            - Name: ss_hdemo_sk
              Type: bigint
            - Name: ss_addr_sk
              Type: bigint
            - Name: ss_store_sk
              Type: bigint
            - Name: ss_promo_sk
              Type: bigint
            - Name: ss_ticket_number
              Type: bigint
            - Name: ss_quantity
              Type: bigint
            - Name: ss_wholesale_cost
              Type: double
            - Name: ss_list_price
              Type: double
            - Name: ss_sales_price
              Type: double
            - Name: ss_ext_discount_amt
              Type: double
            - Name: ss_external_sales_price
              Type: double
            - Name: ss_ext_wholesale_cost
              Type: double
            - Name: ss_ext_list_price
              Type: double
            - Name: ss_ext_tax
              Type: double
            - Name: ss_coupon_amt
              Type: double
            - Name: ss_net_paid
              Type: double
            - Name: ss_net_paid_inc_tax
              Type: double
            - Name: ss_net_profit
              Type: double
          InputFormat: org.apache.hadoop.mapred.TextInputFormat
          Location: s3://tpc-ds-eu-west-1/150GB/store_sales/
          SerdeInfo:
            Parameters:
              field.delim: "|"
            SerializationLibrary: org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe


  CustomerTable:
    # Creating the table waits for the database to be created
    DependsOn: GlueDatabase
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref CFNDatabaseName
      TableInput:
        Name: !Ref CFNTableName2
        Description: Define the first few columns of the flights table
        TableType: EXTERNAL_TABLE
        Parameters: {
    "classification": "csv"
  }
        StorageDescriptor:
          OutputFormat: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat
          Columns:
          - Name: c_customer_sk
            Type: bigint


          - Name: c_customer_id
            Type: string


          - Name: c_current_cdemo_sk
            Type: bigint


          - Name: c_current_hdemo_sk
            Type: bigint


          - Name: c_current_addr_sk
            Type: bigint


          - Name: c_first_shipto_date_sk
            Type: bigint


          - Name: c_first_sales_date_sk
            Type: bigint


          - Name: c_salutation
            Type: string


          - Name: c_first_name
            Type: string


          - Name: c_last_name
            Type: string


          - Name: c_preferred_cust_flag
            Type: string


          - Name: c_birth_day
            Type: bigint


          - Name: c_birth_month
            Type: bigint


          - Name: c_birth_year
            Type: bigint


          - Name: c_birth_country
            Type: string

          - Name: c_login
            Type: string


          - Name: c_email_address
            Type: string


          - Name: c_last_review_date_sk
            Type: bigint
          InputFormat: org.apache.hadoop.mapred.TextInputFormat
          Location: s3://tpc-ds-eu-west-1/150GB/customer/
          SerdeInfo:
            Parameters:
              field.delim: "|"
            SerializationLibrary: org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe
